server:
  port: 8001
spring:
  application:
    name: RetailBank
  datasource:
    url: jdbc:mysql://localhost:3306/yRetailBank
    username: root
    password: root
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL57Dialect
      generate-ddl: true
      show-sql: true